<?xml version="1.0" encoding="utf-8"?><Database Name="BorrowNlend" Class="BorrowNlendDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\sqlexpress;Initial Catalog=BorrowNlend;User ID=sa" SettingsObjectName="BorrowNlend.LinqToSql.Dbml.Properties.Settings" SettingsPropertyName="BorrowNlendConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Operation" Member="Operation">
    <Type Name="Operation">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Amount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Person_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Person_Operation" Member="Person" ThisKey="Person_ID" OtherKey="ID" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Person" Member="Person">
    <Type Name="Person">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Person_Operation" Member="Operation" ThisKey="ID" OtherKey="Person_ID" Type="Operation" />
    </Type>
  </Table>
</Database>